// src/components/Sidebar.vue
<script setup lang="ts">
import { computed } from "vue";
import Icon from "./Icon.vue";
import type { NavConfig, NavItemDef } from "../core/navPrefs";
import type { ViewId } from "../core/navigation";

/**
 * 侧边栏（应用外壳）：按 navPrefs 归一化配置渲染分组/项（折叠、隐藏、
 * 图标覆盖、插件动态项），点击切换视图；ViewId 是宿主导航的视图联合类型
 * （插件视图 id 为字符串，App 按 nav 表动态路由）。
 */
const props = defineProps<{
  activeView: ViewId;
  onSelect: (view: ViewId) => void;
  /** 侧边栏整体折叠（窄模式，仅图标） */
  collapsed: boolean;
  /** 归一化后的导航配置（分组 + 项顺序 + 元数据覆盖） */
  config: NavConfig;
  /** 全部项定义（静态 + 插件 nav 声明） */
  defs: NavItemDef[];
  /** 切换分组折叠（记忆） */
  onToggleGroup: (groupId: string) => void;
}>();

const defById = computed(() => new Map(props.defs.map((d) => [d.id, d])));

/** 归一化后的分组渲染表：过滤隐藏/未知项，空组跳过 */
const groups = computed(() =>
  props.config.groups
    .map((group) => {
      const items = (props.config.order[group.id] ?? [])
        .map((id) => {
          const def = defById.value.get(id);
          if (!def) return null;
          if (props.config.meta[id]?.hidden) return null;
          const meta = props.config.meta[id];
          return { id, label: meta?.label ?? def.label, icon: meta?.icon ?? def.icon };
        })
        .filter((x): x is { id: string; label: string; icon: string } => !!x);
      return { group, items };
    })
    .filter((g) => g.items.length > 0),
);
</script>

<template>
  <nav
    class="sidebar"
    :class="{ collapsed }"
    aria-label="主导航"
    data-part="sidebar"
  >
    <div v-for="g in groups" :key="g.group.id" class="nav-group">
      <button
        v-if="!collapsed"
        class="nav-group-head"
        @click="onToggleGroup(g.group.id)"
        :title="g.group.collapsed ? `展开「${g.group.label}」` : `折叠「${g.group.label}」`"
      >
        <span class="nav-label">{{ g.group.label }}</span>
        <span class="nav-group-caret">
          <Icon :name="g.group.collapsed ? 'chevron-right' : 'chevron-down'" :size="11" />
        </span>
      </button>
      <template v-if="!g.group.collapsed">
        <button
          v-for="item in g.items"
          :key="item.id"
          class="nav-item"
          :class="{ active: item.id === activeView }"
          :aria-current="item.id === activeView ? 'page' : undefined"
          :title="item.label"
          @click="onSelect(item.id as ViewId)"
        >
          <Icon :name="item.icon" :size="16" />
          <span v-if="!collapsed">{{ item.label }}</span>
        </button>
      </template>
    </div>
  </nav>
</template>

// src/components/Sidebar.tsx
import {
  IconCheckSquare,
  IconChevronDown,
  IconChevronRight,
  IconFileText,
  IconFolder,
  IconGear,
  IconGlobe,
  IconGrid,
  IconPuzzle,
  IconSparkle,
} from "./icons";
import type { ComponentType, SVGProps } from "react";
import type { NavConfig, NavItemDef } from "../core/navPrefs";

export type ViewId =
  | "overview"
  | "notes"
  | "plugins"
  | "checklist"
  | "projects"
  | "ai"
  | "blog"
  | "settings";

/** 插件 nav 图标名 → 组件映射（与 navPrefs 的图标名一致，供 meta.icon 覆盖）。 */
export const ICON_MAP: Record<string, ComponentType<SVGProps<SVGSVGElement>>> = {
  "file-text": IconFileText,
  grid: IconGrid,
  check: IconCheckSquare,
  folder: IconFolder,
  sparkle: IconSparkle,
  globe: IconGlobe,
  gear: IconGear,
  puzzle: IconPuzzle,
};

/** 可选图标名（NavSettings 图标下拉用） */
export const ICON_NAMES = Object.keys(ICON_MAP);

interface SidebarProps {
  activeView: ViewId;
  onSelect: (view: ViewId) => void;
  /** 侧边栏整体折叠（窄模式，仅图标） */
  collapsed: boolean;
  /** 归一化后的导航配置（分组 + 项顺序 + 元数据覆盖） */
  config: NavConfig;
  /** 全部项定义（静态 + 插件 nav 声明） */
  defs: NavItemDef[];
  /** 切换分组折叠（记忆） */
  onToggleGroup: (groupId: string) => void;
}

export function Sidebar({
  activeView,
  onSelect,
  collapsed,
  config,
  defs,
  onToggleGroup,
}: SidebarProps) {
  const defById = new Map(defs.map((d) => [d.id, d]));

  return (
    <nav className={`sidebar${collapsed ? " collapsed" : ""}`} aria-label="主导航">
      {config.groups.map((group) => {
        const items = (config.order[group.id] ?? [])
          .map((id) => {
            const def = defById.get(id);
            if (!def) return null;
            if (config.meta[id]?.hidden) return null;
            const meta = config.meta[id];
            const label = meta?.label ?? def.label;
            const Icon = ICON_MAP[meta?.icon ?? def.icon] ?? IconGrid;
            return { id, label, Icon };
          })
          .filter((x): x is { id: string; label: string; Icon: ComponentType<SVGProps<SVGSVGElement>> } => !!x);
        if (items.length === 0) return null;
        const groupCollapsed = !!group.collapsed;

        return (
          <div className="nav-group" key={group.id}>
            {!collapsed && (
              <button
                className="nav-group-head"
                onClick={() => onToggleGroup(group.id)}
                title={groupCollapsed ? `展开「${group.label}」` : `折叠「${group.label}」`}
              >
                <span className="nav-label">{group.label}</span>
                <span className="nav-group-caret">
                  {groupCollapsed ? <IconChevronRight width={11} height={11} /> : <IconChevronDown width={11} height={11} />}
                </span>
              </button>
            )}
            {!groupCollapsed &&
              items.map((item) => {
                const Icon = item.Icon;
                const isActive = item.id === activeView;
                return (
                  <button
                    key={item.id}
                    className={`nav-item${isActive ? " active" : ""}`}
                    aria-current={isActive ? "page" : undefined}
                    title={item.label}
                    onClick={() => onSelect(item.id as ViewId)}
                  >
                    <Icon width={16} height={16} />
                    {!collapsed && <span>{item.label}</span>}
                  </button>
                );
              })}
          </div>
        );
      })}
    </nav>
  );
}
